# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7666bd6a7d036da213904380f8c162464a6f2af14733f9d7017fc40b7b2fd5ba4f38da2a2f037a01f80c73f389869bc55df6b3b7032a0947b99edd953f2d4bb1

test:
  secret_key_base: b0002d6cd5d2dca973b08e72923506574b8c8f04d137e896e5123479f22f4bdbc130b76e0fea48eb8e8c22c584ad24bc932851b3ddb45a83999b88118bc8939e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
